// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
	"webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	userDAO := dao.NewUserDao(db)
	userCache := cache.NewUserRedisCache(cmdable)
	userCacheRepository := repository.NewUserCacheRepository(userDAO, userCache)
	userDevService := service.NewUserDevService(userCacheRepository)
	smsService := ioc.InitSMSService()
	codeCache := cache.NewCodeLocalCache()
	codeCacheRepository := repository.NewCodeCacheRepository(codeCache)
	codeDevService := service.NewCodeDevService(smsService, codeCacheRepository)
	userHandler := web.NewUserHandler(userDevService, codeDevService)
	engine := ioc.InitGin(v, userHandler)
	return engine
}
