// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	v := InitMiddlewares(cmdable)
	db := InitDB()
	userDAO := dao.NewUserDao(db)
	userCache := cache.NewUserRedisCache(cmdable)
	userRepository := repository.NewUserCacheRepository(userDAO, userCache)
	userService := service.NewUserDevService(userRepository)
	smsService := InitSMSService()
	codeCache := cache.NewCodeLocalCache()
	codeRepository := repository.NewCodeCacheRepository(codeCache)
	codeService := service.NewCodeDevService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := InitGin(v, userHandler)
	return engine
}
